include("/home/mccakit/dev/cmake/share/cmake-4.1/Modules/Compiler/Clang-CXX-CXXImportStd.cmake")
set(CMAKE_CXX_STANDARD_LIBRARY libc++)
_cmake_cxx_import_std(26 eval_import_std)
cmake_language(EVAL CODE "${eval_import_std}")
include(/home/mccakit/dev/emscripten/cmake/Modules/Platform/Emscripten.cmake)
add_compile_options(-w -sALLOW_MEMORY_GROWTH -sINITIAL_MEMORY=256MB -flto)
add_link_options(-w -sALLOW_MEMORY_GROWTH -sINITIAL_MEMORY=256MB -flto)
