set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(triple arm64-apple-ios)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_RC_COMPILER _TARGET ${triple})
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_MT llvm-mt)

set(CMAKE_INSTALL_NAME_TOOL /home/mccakit/dev/llvm/bin/llvm-install-name-tool)
set(CMAKE_OBJC_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_OBJC_COMPILER_TARGET ${triple})
set(CMAKE_OBJCXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_OBJCXX_COMPILER_TARGET ${triple})

set(CMAKE_OSX_SYSROOT /home/mccakit/dev/sysroots/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk)
set(CMAKE_OSX_DEPLOYMENT_TARGET 17.0)
set(CMAKE_FIND_ROOT_PATH /home/mccakit/dev/sysroots/Xcode.app)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -nostdinc++ -nostdlib++ -isystem /home/mccakit/dev/libcxx/ios-arm64/include/c++/v1")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L/home/mccakit/dev/libcxx/ios-arm64/lib")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -L/home/mccakit/dev/libcxx/ios-arm64/lib")
link_libraries(libc++.a libc++abi.a libunwind.a)

add_compile_options(-w -flto=thin)
add_link_options(-w -flto=thin)

link_libraries(/home/mccakit/dev/sysroots/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/lib/darwin/libclang_rt.ios.a)
