set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR X86_64)
set(triple x86_64-apple-darwin)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_MT llvm-mt)
set(CMAKE_ASM_COMPILER clang)

set(CMAKE_INSTALL_NAME_TOOL llvm-install-name-tool)
set(CMAKE_OBJC_COMPILER clang)
set(CMAKE_OBJC_COMPILER_TARGET ${triple})
set(CMAKE_OBJCXX_COMPILER clang++)
set(CMAKE_OBJCXX_COMPILER_TARGET ${triple})

set(CMAKE_OSX_SYSROOT /mnt/c/dev/sysroots/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk)
set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0)

add_compile_options(-nostdinc++ -cxx-isystem /home/mccakit/dev/libc++/macos-x64/include/c++/v1)
link_directories(/home/mccakit/dev/libc++/macos-x64/lib)
