set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR X86_64)
set(triple x86_64-windows-msvc)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_MT llvm-mt)
set(CMAKE_ASM_COMPILER clang)

add_compile_options(-Xmicrosoft-windows-sys-root "/home/mccakit/dev/msvc-wine")
add_link_options(-Xmicrosoft-windows-sys-root "/home/mccakit/dev/msvc-wine")
include_directories("/home/mccakit/dev/msvc-wine/Windows Kits/10/Include/10.0.26100.0/um")
include_directories("/home/mccakit/dev/msvc-wine/Windows Kits/10/Include/10.0.26100.0/shared")
set(VULKAN_SDK /mnt/c/VulkanSDK/1.4.313.1)
