set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(triple x86_64-pc-linux-gnu)

set(CMAKE_C_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER /home/mccakit/dev/llvm/bin/llvm-rc)
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR /home/mccakit/dev/llvm/bin/llvm-ar)
set(CMAKE_RANLIB /home/mccakit/dev/llvm/bin/llvm-ranlib)
set(CMAKE_MT /home/mccakit/dev/llvm/bin/llvm-mt)
set(CMAKE_ASM_COMPILER /home/mccakit/dev/llvm/bin/clang)

set(CMAKE_SYSROOT /mnt/c/dev/sysroots/debian-x64)
set(VULKAN_SDK /mnt/c/dev/sysroots/vulkansdk-linux-x86_64-1.4.313.0/1.4.313.0)

add_compile_options(-cxx-isystem /home/mccakit/dev/libc++/linux-x64/include/c++/v1)
link_directories(/home/mccakit/dev/libc++/linux-x64/lib)
