set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(triple arm64-apple-darwin)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_RC_COMPILER _TARGET ${triple})
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_MT llvm-mt)

set(CMAKE_INSTALL_NAME_TOOL llvm-install-name-tool)
set(CMAKE_OBJC_COMPILER clang)
set(CMAKE_OBJC_COMPILER_TARGET ${triple})
set(CMAKE_OBJCXX_COMPILER clang++)
set(CMAKE_OBJCXX_COMPILER_TARGET ${triple})

set(CMAKE_OSX_SYSROOT /home/mccakit/dev/sysroots/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk)
set(CMAKE_OSX_DEPLOYMENT_TARGET 14.0)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -nostdinc++ -nostdlib++ -isystem /home/mccakit/dev/libcxx/macos-x64/include/c++/v1")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L/home/mccakit/dev/libcxx/macos-x64/lib")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -L/home/mccakit/dev/libcxx/macos-x64/lib")
link_libraries(libc++.a libc++abi.a libunwind.a)

add_compile_options(-w -flto=thin)
add_link_options(-w -flto=thin)
