set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(triple arm64-windows-msvc)

set(CMAKE_C_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_RC_COMPILER /home/mccakit/dev/llvm/bin/llvm-rc)
set(CMAKE_RC_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_AR /home/mccakit/dev/llvm/bin/llvm-ar)
set(CMAKE_RANLIB /home/mccakit/dev/llvm/bin/llvm-ranlib)
set(CMAKE_MT /home/mccakit/dev/llvm/bin/llvm-mt)

add_compile_options(-Xmicrosoft-windows-sys-root "/home/mccakit/dev/sysroots/msvc-wine")
add_link_options(-Xmicrosoft-windows-sys-root "/home/mccakit/dev/sysroots/msvc-wine")
include_directories("/home/mccakit/dev/sysroots/msvc-wine/kits/10/include/10.0.26100.0/um")
include_directories("/home/mccakit/dev/sysroots/msvc-wine/kits/10/include/10.0.26100.0/shared")
include_directories("/home/mccakit/dev/sysroots/msvc-wine/kits/10/include/10.0.26100.0/ucrt")
include_directories("/home/mccakit/dev/sysroots/msvc-wine/kits/10/include/10.0.26100.0/winrt")
include_directories("/home/mccakit/dev/sysroots/msvc-wine/vc/tools/msvc/14.44.35207/include")
set(CMAKE_FIND_ROOT_PATH /home/mccakit/dev/sysroots/msvc-wine)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -nostdinc++ -nostdlib++ -isystem /home/mccakit/dev/libcxx/windows-arm64/include/c++/v1")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L/home/mccakit/dev/libcxx/windows-arm64/lib")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -L/home/mccakit/dev/libcxx/windows-arm64/lib")
link_libraries(libc++.lib)
add_compile_definitions(_CRT_STDIO_ISO_WIDE_SPECIFIERS=1)

add_compile_options(-w -flto=thin)
add_link_options(-w -flto=thin)
